name: windows

on:

  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  builds-and-tests:
    
    strategy:
      matrix:
        os: [windows-latest]
        compiler: [ {name: 'intel', version: '2024.0'} ]
        build-type: ["Release"]
        mpi: ["No"]
        mtln: ["Yes"]
        hdf: ["Yes"]

      fail-fast: false
    runs-on: ${{matrix.os}}

    name: ${{matrix.os}} / ${{matrix.compiler.name}} / ${{matrix.build-type}}-mpi(${{matrix.mpi}})-mtln(${{matrix.mtln}})-hdf(${{matrix.hdf}})

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install python wrapper requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'intelmpi'


    - name: Setup intel fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.compiler.name }}
        version: ${{ matrix.compiler.version }}

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake build
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DSEMBA_FDTD_ENABLE_MPI=${{matrix.mpi}} \
          -DSEMBA_FDTD_ENABLE_HDF=${{matrix.hdf}} \
          -DSEMBA_FDTD_ENABLE_MTLN=${{matrix.mtln}}
        cmake --build build -j 

    - name: Run unit tests 
      run: build/bin/fdtd_tests.exe

    - name: Run python tests (except codemodel)
      env:
        SEMBA_FDTD_ENABLE_MPI: ${{ matrix.mpi }}
        SEMBA_FDTD_ENABLE_MTLN: ${{ matrix.mtln }}
        SEMBA_FDTD_ENABLE_HDF: ${{ matrix.hdf }}
      run: python -m pytest -m 'not codemodel' test/
        
